import { Carlito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const carlito = Carlito({ 
  weight: ['400','700'],
  subsets: ["latin"],
  display: 'swap'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={carlito.className}>
        <div className="flex flex-col h-screen divide-y">
          <div className="flex-grow">{children}</div>
          <Navbar />
        </div>
      </body>
    </html>
  );
}
